


// Project header
#include "../main/main.h"

// Task header
#include "luces_puertas.h"


// ------ Public variable ------------------------------------------

// See scheduler for definition
extern uint32_t Fault_code_G;
extern uint32_t SWITCH_PUERTA_LIMPIA, SWITCH_PUERTA_SUCIA;
void LUCES_PUERTAS_Init(void)
{
	//LUZ VERDE ENTRADA
	Chip_IOCON_PinMux(LPC_IOCON, LUZ_VERDE_ENTRADA_PORT, LUZ_VERDE_ENTRADA_PIN, LUZ_VERDE_ENTRADA_PIN_MODE, LUZ_VERDE_ENTRADA_PIN_FUNC);
	Chip_GPIO_SetPinDIROutput(LPC_GPIO, LUZ_VERDE_ENTRADA_PORT, LUZ_VERDE_ENTRADA_PIN);
	Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_VERDE_ENTRADA_PORT, LUZ_VERDE_ENTRADA_PIN, true); // ARRANCA PRENDIDA
	//LUZ ROJA ENTRADA
	Chip_IOCON_PinMux(LPC_IOCON, LUZ_ROJA_ENTRADA_PORT, LUZ_ROJA_ENTRADA_PIN, LUZ_ROJA_ENTRADA_PIN_MODE, LUZ_ROJA_ENTRADA_PIN_FUNC);
	Chip_GPIO_SetPinDIROutput(LPC_GPIO, LUZ_ROJA_ENTRADA_PORT, LUZ_ROJA_ENTRADA_PIN);
	Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_ROJA_ENTRADA_PORT, LUZ_ROJA_ENTRADA_PIN, false); // ARRANCA APAGADA

	//LUZ VERDE SALIDA
		Chip_IOCON_PinMux(LPC_IOCON, LUZ_VERDE_SALIDA_PORT, LUZ_VERDE_SALIDA_PIN, LUZ_VERDE_SALIDA_PIN_MODE, LUZ_VERDE_SALIDA_PIN_FUNC);
		Chip_GPIO_SetPinDIROutput(LPC_GPIO, LUZ_VERDE_SALIDA_PORT, LUZ_VERDE_SALIDA_PIN);
		Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_VERDE_SALIDA_PORT, LUZ_VERDE_SALIDA_PIN, true); // ARRANCA PRENDIDA
		//LUZ ROJA SALIDA
		Chip_IOCON_PinMux(LPC_IOCON, LUZ_ROJA_SALIDA_PORT, LUZ_ROJA_SALIDA_PIN, LUZ_ROJA_SALIDA_PIN_MODE, LUZ_ROJA_SALIDA_PIN_FUNC);
		Chip_GPIO_SetPinDIROutput(LPC_GPIO, LUZ_ROJA_SALIDA_PORT, LUZ_ROJA_SALIDA_PIN);
		Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_ROJA_SALIDA_PORT, LUZ_ROJA_SALIDA_PIN, false); // ARRANCA APAGADA
}



void LUCES_PUERTAS_Update(void)
{
extern uint8_t ESTADO_GENERAL;
extern uint8_t ESTADO_CERRADURA_SALIDA, ESTADO_CERRADURA_ENTRADA;
static uint32_t contador_emergencia, ESTADO_LEDS, primera;

if(ESTADO_GENERAL!=EMERGENCIA)
{
	if( ESTADO_CERRADURA_SALIDA == TRABADO && ESTADO_CERRADURA_ENTRADA == TRABADO )
	{ Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_ROJA_ENTRADA_PORT, LUZ_ROJA_ENTRADA_PIN, true); // ENCIENDO LUZ ROJA
	Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_ROJA_SALIDA_PORT, LUZ_ROJA_SALIDA_PIN, true); // ENCIENDO LUZ ROJA
	Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_VERDE_ENTRADA_PORT, LUZ_VERDE_ENTRADA_PIN, false);
	Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_VERDE_SALIDA_PORT, LUZ_VERDE_SALIDA_PIN, false);
	}
	else
	{
		if( SWITCH_PUERTA_LIMPIA == SW_NOT_PRESSED) // SI EL SWITCH SE PRESIONA, ENCIENDO LA LUZ ROJA Y APAGO LA VERDE
			{
			Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_ROJA_ENTRADA_PORT, LUZ_ROJA_ENTRADA_PIN, true); // ENCIENDO LUZ ROJA
			Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_VERDE_ENTRADA_PORT, LUZ_VERDE_ENTRADA_PIN, false); // APAGO LUZ VERDE
				}
		if( SWITCH_PUERTA_LIMPIA == SW_PRESSED) // SI EL SWITCH SE PRESIONA, ENCIENDO LA LUZ ROJA Y APAGO LA VERDE
			{
			Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_ROJA_ENTRADA_PORT, LUZ_ROJA_ENTRADA_PIN, false); // ENCIENDO LUZ VERDE
			Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_VERDE_ENTRADA_PORT, LUZ_VERDE_ENTRADA_PIN, true); // APAGO LUZ ROJA
				}

		if( SWITCH_PUERTA_SUCIA == SW_NOT_PRESSED) // SI EL SWITCH SE PRESIONA, ENCIENDO LA LUZ ROJA Y APAGO LA VERDE
				{
				Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_ROJA_SALIDA_PORT, LUZ_ROJA_SALIDA_PIN, true); // ENCIENDO LUZ ROJA
				Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_VERDE_SALIDA_PORT, LUZ_VERDE_SALIDA_PIN, false); // APAGO LUZ VERDE
					}

		if( SWITCH_PUERTA_SUCIA == SW_PRESSED) // SI EL SWITCH SE PRESIONA, ENCIENDO LA LUZ ROJA Y APAGO LA VERDE
				{
				Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_ROJA_SALIDA_PORT, LUZ_ROJA_SALIDA_PIN, false); // ENCIENDO LUZ VERDE
				Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_VERDE_SALIDA_PORT, LUZ_VERDE_SALIDA_PIN, true); // APAGO LUZ ROJA
					}
	}
}
else {	Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_VERDE_SALIDA_PORT, LUZ_VERDE_SALIDA_PIN, false); //APAGO AMBAS VERDES
		Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_VERDE_ENTRADA_PORT, LUZ_VERDE_ENTRADA_PIN, false); //APAGO AMBAS VERDES
			if(primera==0)
			{
				Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_ROJA_ENTRADA_PORT, LUZ_ROJA_ENTRADA_PIN, true);
				Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_ROJA_SALIDA_PORT, LUZ_ROJA_SALIDA_PIN, true);
				ESTADO_LEDS = ON;
				primera++;
			}

		if(ESTADO_LEDS == OFF && contador_emergencia == 50){
		Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_ROJA_ENTRADA_PORT, LUZ_ROJA_ENTRADA_PIN, true);
		Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_ROJA_SALIDA_PORT, LUZ_ROJA_SALIDA_PIN, true);
		ESTADO_LEDS = ON;
		contador_emergencia=0;
		}
		if(ESTADO_LEDS == ON && contador_emergencia == 50)
		{
		Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_ROJA_ENTRADA_PORT, LUZ_ROJA_ENTRADA_PIN, false);
		Chip_GPIO_WritePortBit(LPC_GPIO, LUZ_ROJA_SALIDA_PORT, LUZ_ROJA_SALIDA_PIN, false);
		ESTADO_LEDS = OFF;
		contador_emergencia=0;
		}
		contador_emergencia++;
}

}


/*------------------------------------------------------------------*-
  ---- END OF FILE -------------------------------------------------
-*------------------------------------------------------------------*/
